{{- if .Values.customizer.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: customizer-scc-nemo-customizer-scc
  namespace: {{ .Values.namespace.name }}
  labels:
    component: customizer
    app.kubernetes.io/name: nemo-instances
    app.kubernetes.io/component: customizer
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames: ['nemo-customizer-scc']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customizer-scc-nemo-customizer-scc-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    component: customizer
    app.kubernetes.io/name: nemo-instances
    app.kubernetes.io/component: customizer
subjects:
- kind: ServiceAccount
  name: {{ .Values.customizer.name }}
  namespace: {{ .Values.namespace.name }}
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: customizer-scc-nemo-customizer-scc
  apiGroup: rbac.authorization.k8s.io
{{- end }}

