{{- if .Values.nimPipelineEmbedding.enabled }}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMPipeline
metadata:
  name: {{ .Values.nimPipelineEmbedding.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  services:
    - name: {{ .Values.nimPipelineEmbedding.serviceName }}
      enabled: true
      spec:
        env:
          - name: NIM_PEFT_SOURCE
            value: http://{{ .Values.entitystore.name }}.{{ .Values.namespace.name }}.svc.cluster.local:8000
          - name: NIM_PEFT_REFRESH_INTERVAL
            value: "180"
          - name: NIM_MAX_CPU_LORAS
            value: "16"
          - name: NIM_MAX_GPU_LORAS
            value: "8"
          - name: NIM_GUIDED_DECODING_BACKEND
            value: fast_outlines
        image:
          repository: {{ .Values.nimPipelineEmbedding.image.repository }}
          tag: {{ .Values.nimPipelineEmbedding.image.tag | quote }}
          pullPolicy: {{ .Values.nimPipelineEmbedding.image.pullPolicy }}
          pullSecrets:
          - {{ .Values.nimPipelineEmbedding.pullSecret }}
        authSecret: {{ .Values.nimPipelineEmbedding.authSecret }}
        storage:
          nimCache:
            name: {{ .Values.nimPipelineEmbedding.nimCacheName }}
            profile: ''
        replicas: {{ .Values.nimPipelineEmbedding.replicas }}
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.nimPipelineEmbedding.resources.limits.gpu }}
        # GPU node tolerations for OpenShift/Kubernetes clusters with tainted GPU nodes
        tolerations:
{{- toYaml .Values.nimPipelineEmbedding.tolerations | nindent 10 }}
        expose:
          service:
            type: ClusterIP
            port: 8000
{{- end }}

