{{- if .Values.install.jupyter }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jupyter.pvcName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: jupyter
spec:
  {{- if ne (include "nemo-infra.storageClass" .) "" }}
  storageClassName: {{ include "nemo-infra.storageClass" . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jupyter.storage.size }}
{{- end }}

