{{- if .Values.install.evaluator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-executor
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: argo
imagePullSecrets:
  - name: nvcrimagepullsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-executor-role
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: argo
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-executor-role-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: argo
subjects:
- kind: ServiceAccount
  name: argo-workflows-executor
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: argo-workflows-executor-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}

