{{- if .Values.install.evaluator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: milvus
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: milvus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: milvus-scc-anyuid
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: milvus
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames: ['anyuid']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: milvus-scc-anyuid-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: evaluator
    subcomponent: milvus
subjects:
- kind: ServiceAccount
  name: milvus
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: milvus-scc-anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end }}

