{{- if .Values.install.jupyter }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: jupyter
data:
  {{- if .Values.jupyter.notebookContent }}
  {{ .Values.jupyter.notebookName }}: |-
{{ .Values.jupyter.notebookContent | indent 4 }}
  {{- end }}
  {{- if .Values.jupyter.configContent }}
  {{ .Values.jupyter.configName }}: |-
{{ .Values.jupyter.configContent | indent 4 }}
  {{- end }}
{{- end }}

