{{- if .Values.install.jupyter }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-scc-anyuid
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: jupyter
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames: ['anyuid']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-scc-anyuid-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: jupyter
subjects:
- kind: ServiceAccount
  name: jupyter
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: jupyter-scc-anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end }}

