{{- if .Values.install.jupyter }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nemo-infra.labels" . | nindent 4 }}
    component: jupyter
{{- end }}

