{{- if and .Values.llamastack.enabled .Values.llamastack.useBearerToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.llamastack.serviceAccountName }}-token-secret
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.llamastack.serviceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}

