{{- if and .Values.llamastack.enabled .Values.llamastack.useBearerToken .Values.llamastack.createServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.llamastack.serviceAccountName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}


